In [1]:
%load_ext autoreload
%autoreload 2

import calciowiki as cw
import logging
logging.basicConfig(level=logging.DEBUG)

In [108]:
j='Juventus_Football_Club_2021-2022'
x = cw.WikiSeasonIt(title=j)

DEBUG:root:Getting Page: Juventus_Football_Club_2021-2022
DEBUG:root:Processing season for club: Juventus FC.

rig















rig






rig







rig
rig































rig


aut


rig




rig


aut






rig

In [109]:
x.season['events'].head()

  time    player  type desc    match_time      team season
0   51   Pereyra  goal  pen  1.629650e+09   Udinese  21-22
1   83  Deulofeu  goal       1.629650e+09   Udinese  21-22
0    3    Dybala  goal       1.629650e+09  Juventus  21-22
1   23  Cuadrado  goal       1.629650e+09  Juventus  21-22
0   21   Mancuso  goal       1.630176e+09    Empoli  21-22

In [4]:
import mwparserfromhell
import pandas as pd

In [61]:
classifica = {}
classifica['sa'] = "Serie_A_2021-2022"
classifica['saf'] = "Serie_A_2021-2022_(calcio_femminile)"
classifica['sc'] = "Serie_C_2021-2022"

In [110]:
x = cw.WikiClassifica(classifica['sa'])

DEBUG:root:Getting Page: Serie_A_2021-2022

In [95]:
display(x.classifica)

,Position,Team,Points,Played,Won,Draw,Lost,Goals Scored,Goals Against,Goal Difference
0,1,Milan,56,26,17,5,4,52,28,24
1,2,Inter,54,24,16,6,2,55,20,35
2,3,Napoli,53,25,16,5,4,46,17,29
3,4,Juventus,47,26,13,8,5,38,23,15
4,5,Atalanta,44,24,12,8,4,46,29,17
5,6,Lazio,42,25,12,6,7,52,39,13
6,7,Roma,41,26,12,5,9,44,34,10
7,8,Fiorentina,39,24,12,3,9,43,34,9
8,9,Verona,37,26,10,7,9,49,42,7
9,10,Torino,33,25,9,6,10,32,26,6
10,11,Empoli,31,26,8,7,11,38,50,-12
11,12,Sassuolo,30,25,7,9,9,41,44,-3
12,13,Bologna,28,24,8,4,12,29,40,-11
13,14,Spezia,26,25,7,5,13,27,46,-19
14,14,Sampdoria,26,26,7,5,14,35,42,-7
15,16,Udinese,24,23,5,9,9,30,40,-10
16,17,Venezia,21,24,5,6,13,22,43,-21
17,17,Cagliari,21,25,4,9,12,25,46,-21
18,19,Genoa,15,25,1,12,12,21,46,-25
19,20,Salernitana,14,24,3,5,16,19,55,-36